name: 'Update Assembly Version'
description: 'Updates assembly attributes in given file according to config'
inputs:
  assembly-file:
    description: 'Path to file that contains assembly version'
    required: true
  increase-build:
    description: 'Whether to increase build number'
    default: true
  increase-release:
    description: 'Whether to increase release number'
    default: false
  tag:
    description: 'Assembly tag'
  GITHUB_TOKEN:
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
