name: 'Update Assembly Version'
description: 'Updates assembly attributes in given file according to config'
inputs:
  assembly-file:
    description: 'Path to file that contains assembly version'
    required: true
  increase-major:
    description: 'Whether to increase major number'
    default: false
  increase-minor:
    description: 'Whether to increase minor number'
    default: false
  increase-build:
    description: 'Whether to increase build number'
    default: true
  branch:
    description: 'Branch to which commit will be made'
  tag:
    description: 'Assembly tag'
  GITHUB_TOKEN:
    description: 'Github access token'
outputs:
  oldVersion:
    description: 'Old version from file'
  newVersion:
    description: 'New version'
runs:
  using: 'node12'
  main: 'dist/index.js'
