name: Build and commit action

on:
  push:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Compile typescript
        run: npm run compile
      - name: Build into single file
        run: npm run build
      - name: Commit build
        run: |
          git config user.name "update-assembly-version"
          git config user.email "<>"
          git add -f dist
          git commit -m "Add dist"
      - name: Tag commit
        run: |
          tag=$(git describe --tags --abbrev=0);
          minor=$(echo $tag | grep -oP "^v\d+\.\d+$" | grep -oP "\.\d+" | grep -oP "\d+");
          minor=$(($minor+1))
          newTag=$(node -e 'console.log(process.argv[1].replace(/^(v\d+\.)(\d+)$/, `$1${process.argv[2]}`));' $tag "$minor")
          git tag $newTag
      - name: Push
        run: |
          git push