name: Build and publish action

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Compile typescript
        run: npm run compile
      - name: Build into single file
        run: npm run build
      - name: Commit build
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Add dist'
          force-add: 'true'
          files: dist


