name: Test action

on:
  - pull_request

jobs:
  build-version:
    name: Update build version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Install ts-node
        run: npm install -g ts-node
      - name: Save current version
        run: ts-node scripts/saveCurrent.ts
      - name: Compile typescript
        run: npm run compile
      - name: Build into single file
        run: npm run build
      - name: Run action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assembly-file: AssemblyVersion.cs
          increase-build: true
          make-commit: false
      - name: Check build
        run: |
          ts-node scripts/checkBuild.ts
      - name: Save current version
        run: ts-node scripts/saveCurrent.ts
      - name: Run action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assembly-file: AssemblyVersion.cs
          tag: 'beta'
          make-commit: false
      - name: Check build
        run: |
          ts-node scripts/checkTag.ts
      - name: Save current version
        run: ts-node scripts/saveCurrent.ts
      - name: Run action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assembly-file: AssemblyVersion.cs
          increase-minor: true
          make-commit: false
      - name: Check minor
        run: |
          ts-node scripts/checkMinor.ts
      - name: Save current version
        run: ts-node scripts/saveCurrent.ts
      - name: Run action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assembly-file: AssemblyVersion.cs
          increase-major: true
          make-commit: false
      - name: Check major
        run: |
          ts-node scripts/checkMajor.ts
