name: Test action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Original file
          path: AssemblyVersion.cs
      - name: Save current version
        run: |
          old_version=$( cat AssemblyVersion.cs | grep -oP '(?<=AssemblyVersion\(\")[\d\w-\.]*(?=\")' );
          echo "OLD_VERSION=$old_version" >> $GITHUB_ENV;
      - name: Run action
        uses: keebox/update-assembly-version@v0.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assembly-file: AssemblyVersion.cs
          increase-build: true
          increase-release: false
      - name: Check new version
        run: |
          new_version=$( cat AssemblyVersion.cs | grep -oP '(?<=AssemblyVersion\(\")[\d\w-\.]*(?=\")' );
          echo $new_version
          echo $OLD_VERSION
          new_arr=($(echo $new_version | tr "." "\n"))
          old_arr=($(echo $OLD_VERSION | tr "." "\n"))
          res=$((new_arr[1]-old_arr[1]))
          echo $res
          if [ $res != 1 ]
          then
            exit 1
          else
            echo "All good"
          fi
